language: generic
sudo: required
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - docker build -t pabloeng05/app-mirval-ngbasic  -f Dockerfile.dev .

script:
  - docker run -e CI=true pabloeng05/app-mirval-ngbasic npm run test -- --watch=false

deploy:
  skip_cleanup: true 
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'app-mirval-ngbasic'
  env: 'Appmirvalngbasic-env'
  bucket_name: 'elasticbeanstalk-us-east-1-392868714247'
  bucket_path: 'app-mirval-ngbasic'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY